name: Build Clicker APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk \
        build-essential autoconf libtool pkg-config \
        zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
        libstdc++6 libgtk-3-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Set environment variables (IMPORTANT FIX)
      run: |
        echo "ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk" >> $GITHUB_ENV
        echo "ANDROIDAPI=33" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Clicker-APK
        path: bin/*.apk
